### PR TITLE
Use the "fritzbox" bucket in dashboards

### PR DESCRIPTION
**Pull request by deltaphi**
Update the influxdbv2 dashboards to use the bucket named "fritzbox" (default name used by the script when creating the bucket) instead of requiring the data source default to be set to the fritzinfluxdb bucket. This is really handy if you use the same influxdb/grafana instances for multiple buckets and dashboards.

In case you do not want to accept this pull request, a note in the documentation how to patch the dashboard files would be appreciated.

### CODE REVIEW

**Comment by bb-Ricardo** [comment]
Hi,

Thank you for the PR. I still try to understand the issue which this PR meant to solve. The bucket name is a variable which is defined as the default bucket for the defined datasource.

**Comment by deltaphi** [comment]
> bucket name is a variable which is defined as the default bucket for the defined datasource.

And that’s exactly the problem :) I use another bucket on the same influxdb instance for Home Assistant. I also use the same grafana instance for dashboards related to Home Assistant and Fritzinfluxdb. Add it is the same influxdb instance, I already have the data source set up. But  the Home Assistant Dashboard were there first, so the default bucket is already taken up by them.

This patch enables using the same data source for both Home Assistant and Fritzinfluxdb buckets.

**Comment by bb-Ricardo** [comment]
Ahh, that's what I assumed. How about adding an additional dedicated datasource for that purpose?

Should also think about how to progress with this whole influxdb mess.

Have you used VictoriaMetrics?

**Comment by deltaphi** [comment]
> Ahh, that's what I assumed. How about adding an additional dedicated datasource for that purpose?

I basically expected that the solution would be something as annoying as that. I don't feel like dealing with the Token stuff and figuring out what goes where *again*, though, so I'm flat out refusing to try when I already have a working solution :D.

I can understand if you don't want to accept this PR - but then maybe adding a hint in the top-level `README.md` that you can just text-replace the bucket name in the JSON files would be helpful.

> Should also think about how to progress with this whole influxdb mess.
> 
> Have you used VictoriaMetrics?

Entirely different topic, so maybe a discussion for a different issue? My answer: No, I haven't used VictoriaMetrics. Glancing over the Website, it appears to be similar to InfluxDB: A time series database developed as open source (how open?)  in a basic tier and available as paid-for license in a more advanced tier, developed by a for-profit company - just like InfluxDB. Personally, I wouldn't trust them to do any better than InfluxDB does.

Without having done more research than opening like the first hit on google: [OpenTSDB](http://opentsdb.net) appears to be a true open source project - and can also be used as a data source for Grafana.

**Pull request closed without merging**
